[1;92mINFO [2024-06-17 07:19:29 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:19:29 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:29 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:29 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:30 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:19:30 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:19:30 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:30 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:19:31 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:19:31 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:33 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:19:33 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:19:33 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:33 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:34 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:19:35 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:19:36 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:19:37 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:19:39 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:19:46 - start_command.py:32] - user not admin : 232443605[0m
[1;92mINFO [2024-06-17 07:19:48 - start_command.py:32] - user not admin : 232443605[0m
[1;92mINFO [2024-06-17 07:20:09 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:11 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:13 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:14 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:16 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:20:22 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:20:22 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:22 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:22 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:24 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:20:24 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:20:24 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:24 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:24 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:24 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:20:25 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:20:25 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:20:25 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:25 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:25 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:27 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:20:27 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:20:27 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:27 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:27 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:27 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:20:43 - account_manager.py:245] - Telegram says: [400 PHONE_CODE_INVALID] - The confirmation code is invalid (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-17 07:20:56 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:21:15 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:21:24 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:21:24 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:24 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:24 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:26 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:21:26 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:26 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:26 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:26 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:26 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:21:27 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:21:27 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:21:27 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:27 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:28 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:29 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:21:29 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:29 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:29 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:29 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:29 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:21:37 - account_manager.py:200] - Telegram says: [401 SESSION_PASSWORD_NEEDED] - The two-step verification is enabled and a password is required (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-17 07:21:43 - account_manager.py:225] - Telegram says: [400 USERNAME_NOT_OCCUPIED] - The username is not occupied by anyone (caused by "contacts.ResolveUsername")[0m
[1;92mINFO [2024-06-17 07:21:43 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:21:43 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:43 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:21:43 - session.py:180] - Session stopped[0m
[1;93mWARNING [2024-06-17 07:21:43 - utils.py:72] - running container for phone : +46765147252[0m
[1;92mINFO [2024-06-17 07:21:56 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:21:58 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:24:01 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:24:03 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:24:03 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:24:03 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:24:03 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:24:03 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:24:42 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:42 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:24:42 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:24:42 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:24:43 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:24:46 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:24:47 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:24:49 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:24:57 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:24:57 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:57 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:24:57 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:24:58 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:24:58 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:24:58 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:58 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:24:59 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:24:59 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:24:59 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:24:59 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:59 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:25:00 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:25:02 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:25:02 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:25:02 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:25:02 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:25:02 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:25:02 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:25:08 - account_manager.py:185] - Telegram says: [401 SESSION_PASSWORD_NEEDED] - The two-step verification is enabled and a password is required (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-17 07:25:12 - account_manager.py:194] - BAGY9NIAFoEHRPlSUjkmVgVcApezwK-h0ZPb2XA7FQ-3_tIeC-f9ql0QuZviujF5HuBP4_jgg_pCXuc46dGCqD0cv0nfB_N32Fb0VRqBYDSv3ENowOUBB7YakP--786EG35FkwdPLuI5-KXKBMRX4V9aSNd_Z7DyoaefTlVlph4K5j0nSlMJnDZ0sdVFKN8xSrYMHh4NaNsylkkO4YnCwOSoixNZn-KQXSt_99ICuWUa2hS3wgG-HJl2eCTpQsTWhWY_VR942ZdK8_IPRUBYQYqQDUMVcAfH_VUjMgbwwvJF7S6OfF0-wLo0HM_Fvkp9h3ns8-Lqkf6lKkGAJLefacLk4L0KlQAAAAFIjDkpAA[0m
[1;92mINFO [2024-06-17 07:25:12 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:25:12 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:25:12 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:25:12 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:25:13 - start_command.py:32] - user not admin : 5512116521[0m
[1;93mWARNING [2024-06-17 07:25:13 - utils.py:72] - running container for phone : +46765147252[0m
[1;93mWARNING [2024-06-17 07:25:15 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:17 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:19 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:20 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:22 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:23 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:26 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:28 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:29 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:25:43 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:25:43 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:25:43 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:25:43 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:25:43 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:25:43 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:27:33 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:27:33 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:27:33 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:27:33 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:27:33 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:27:33 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:27:33 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:27:33 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:27:33 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:27:34 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:27:34 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:27:34 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:27:34 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:27:34 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:27:34 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:27:39 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;92mINFO [2024-06-17 07:27:41 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:27:43 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:27:44 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:27:46 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:27:48 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:29:49 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:29:54 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:29:54 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:29:54 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:29:54 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:29:54 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:32:23 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:32:23 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:32:24 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:32:24 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:32:24 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:32:24 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:32:24 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:32:24 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:32:24 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:32:25 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:32:25 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:32:25 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:32:25 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:32:25 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:32:25 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:32:27 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:32:30 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:32:31 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:32:34 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:37:10 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:37:15 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:37:15 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:37:15 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:37:15 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:37:15 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:37:17 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:37:17 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:37:18 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:37:18 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:37:18 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:37:18 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:37:18 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:37:18 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:37:18 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:37:19 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:37:19 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:37:19 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:37:19 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:37:19 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:37:19 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:37:21 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:37:23 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:37:24 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:37:26 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:37:30 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:37:31 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:37:33 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:37:33 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:37:33 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:37:33 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:37:33 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:39:30 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:39:30 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:39:31 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:39:31 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:39:31 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:39:31 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:39:31 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:39:31 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:39:31 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:39:32 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:39:32 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:39:32 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:39:32 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:39:32 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:39:32 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:39:34 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:39:36 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:39:38 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:39:39 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:44:50 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:44:50 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:44:50 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:44:50 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:44:51 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:44:51 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:44:51 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:44:51 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:44:51 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:44:52 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:44:52 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:44:52 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:44:52 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:44:52 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:44:52 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:44:54 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:44:56 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:44:57 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:44:59 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;91mERROR [2024-06-17 07:44:59 - dispatcher.py:253] - 'str' object has no attribute 'text'[0m
Traceback (most recent call last):
  File "/home/freeguy/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/freeguy/.local/lib/python3.10/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/freeguy/.local/lib/python3.10/site-packages/pyromod/listen/callback_query_handler.py", line 146, in resolve_future_or_callback
    await self.original_callback(client, query, *args)
  File "/home/freeguy/Desktop/project/selfbot/app/plugins/account_manager.py", line 51, in account_manager_handler
    await create_session(client , call )
  File "/home/freeguy/Desktop/project/selfbot/app/plugins/account_manager.py", line 63, in create_session
    if phone_number and phone_number.text and check_phone_number(phone_number.text) :
AttributeError: 'str' object has no attribute 'text'
[1;92mINFO [2024-06-17 07:45:02 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:45:06 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:45:06 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:45:06 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:45:06 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:45:06 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:45:58 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:45:58 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:45:58 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:45:58 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:45:58 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:45:58 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:45:58 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:45:58 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:45:58 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:45:59 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:45:59 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:45:59 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:45:59 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:45:59 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:45:59 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:46:02 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:46:04 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:46:06 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:46:07 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:46:07 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:46:07 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:07 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:07 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:09 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:46:09 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:09 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:09 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:09 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:09 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:46:10 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:46:10 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:46:10 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:46:10 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:10 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:11 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:13 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:46:13 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:13 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:13 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:13 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:13 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:46:14 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:46:14 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:46:14 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:46:14 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:46:14 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:46:22 - account_manager.py:98] - Telegram says: [401 SESSION_PASSWORD_NEEDED] - The two-step verification is enabled and a password is required (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-17 07:46:29 - account_manager.py:106] - BAGY9NIAPBVXPwEv9JXeh--kxOi7D2Cm4uPyih3yLIHj6zjGlQsJKaoQHNNqhmYuPnD76ZsQKuwHt-JEH3b-KgOvidzHWlA-yRF8TjjMOwivqY8xkhfiY5_YZDlBNU1bGYODVTHMuO3BRfYrMeA2z85Dl9fujLLjJZwW_eD2Oqg3GRH5PstBmjMkhZ5PXgzJIR31d4qbOEvPeGZgg8y6zRgy-d17rfO60HI-RkMtrxp8MCny_awxh2pkPgsAo2jHourEmbd7zeEYuSNRpmbfN-rm6s-BZfr8wxJrIMIQRytSm7cSiTRl4noSDTRPhEi-WknKwX4apPNiPbx9NMnwZkHVpImq4AAAAAFIjDkpAA[0m
[1;92mINFO [2024-06-17 07:46:29 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:46:29 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:29 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:46:29 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:46:36 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:46:38 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:46:38 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:46:38 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:38 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:46:38 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:46:46 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:46 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:46 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:46 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:46:47 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:46:47 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:46:47 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:46:47 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:46:47 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:46:47 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:46:47 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:46:47 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:46:47 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:46:47 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:46:47 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;93mWARNING [2024-06-17 07:46:49 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:46:50 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:46:52 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:46:52 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:46:52 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:52 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:52 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:54 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:46:54 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:54 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:54 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:54 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:54 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:46:54 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:46:54 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:46:54 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:46:54 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:46:54 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:46:55 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:46:55 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:55 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:46:55 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:46:55 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:46:55 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:55 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:55 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:57 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:46:57 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:46:57 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:46:57 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:46:58 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:46:58 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:46:58 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:46:58 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:46:58 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:46:58 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:46:58 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:47:05 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:47:06 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:47:10 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:47:15 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:47:17 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:47:17 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:47:17 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:47:17 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:47:17 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 09:47:15 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 09:47:15 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 09:47:15 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 09:47:15 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 09:47:16 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 09:47:16 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 09:47:16 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 09:47:16 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 09:47:16 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 09:47:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 09:47:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 09:47:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 09:47:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 09:47:17 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 09:47:17 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 09:47:21 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:47:23 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:47:25 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:47:27 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:47:28 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:47:29 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 09:47:29 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 09:47:29 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 09:47:29 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 09:47:30 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 09:47:31 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 09:47:31 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 09:47:31 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 09:47:31 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 09:47:31 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 09:47:31 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 09:47:32 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 09:47:32 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 09:47:32 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 09:47:32 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 09:47:32 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 09:47:32 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 09:47:34 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 09:47:34 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 09:47:34 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 09:47:34 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 09:47:35 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 09:47:35 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 09:47:35 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 09:47:35 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 09:47:35 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 09:47:35 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 09:47:35 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 09:50:39 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 09:50:39 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 09:50:39 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 09:50:39 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 09:50:40 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 09:50:40 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 09:50:40 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 09:50:40 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 09:50:40 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 09:50:41 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 09:50:41 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 09:50:41 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 09:50:41 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 09:50:41 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 09:50:41 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 09:50:55 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:50:56 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:50:58 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:51:05 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:51:06 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:51:07 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:51:09 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 09:54:38 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:40 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:42 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:44 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:45 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:46 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:47 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:48 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:49 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:50 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:54:51 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;92mINFO [2024-06-17 09:55:07 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:55:09 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:55:11 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:55:12 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:55:13 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:55:15 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 09:55:16 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;92mINFO [2024-06-17 09:56:45 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 09:56:45 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 09:56:45 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 09:56:45 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 09:56:45 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 09:56:45 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 10:04:05 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 10:04:05 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 10:04:06 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 10:04:06 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 10:04:06 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 10:04:06 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 10:04:06 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 10:04:06 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 10:04:06 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 10:04:06 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 10:04:06 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 10:04:06 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 10:04:06 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 10:04:06 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 10:04:06 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 10:04:12 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 10:04:13 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 10:04:15 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 10:04:19 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 10:04:20 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 10:07:52 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 10:07:56 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 10:07:56 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 10:07:56 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 10:07:56 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 10:07:56 - session.py:180] - Session stopped[0m
<<<<<<< HEAD
[1;92mINFO [2024-06-18 16:18:39 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:18:39 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:18:39 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:18:39 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:18:39 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:18:39 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:18:39 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:18:39 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:18:39 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:18:40 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-18 16:18:40 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-18 16:18:40 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:18:40 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:18:40 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-18 16:18:40 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:18:42 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:18:44 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:18:46 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:18:48 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:18:49 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:18:50 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:18:51 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 16:18:52 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-18 16:18:54 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:18:54 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:18:54 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:18:54 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:18:54 - session.py:180] - Session stopped[0m
=======
[1;92mINFO [2024-06-17 18:15:10 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 18:15:10 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:10 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:11 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:13 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 18:15:13 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:15:13 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:13 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:13 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:13 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:15:14 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:15:14 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 18:15:14 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 18:15:14 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:14 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:14 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:16 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 18:15:16 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:15:16 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:16 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:16 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:16 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:15:17 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:15:17 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:15:17 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:15:17 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:15:17 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:15:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 18:15:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 18:15:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:15:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:15:17 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 18:15:17 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:15:18 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:15:20 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:15:22 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:15:25 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:15:26 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:15:27 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 18:15:27 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 18:15:27 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:27 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:27 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:29 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 18:15:29 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:15:29 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:29 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:29 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:29 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:15:30 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:15:30 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 18:15:30 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 18:15:30 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:30 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:31 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:32 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 18:15:32 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:15:32 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:15:32 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:15:33 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:15:33 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:15:33 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:15:33 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:15:33 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:15:33 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:15:33 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 18:15:44 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:15:45 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:15:47 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 18:17:24 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 18:17:27 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:17:27 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:17:27 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:17:27 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:17:27 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 18:17:28 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:17:28 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:17:28 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:17:28 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:17:29 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:17:29 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:17:29 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:17:29 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:17:29 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:17:30 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 18:17:30 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 18:17:30 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:17:30 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:17:30 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 18:17:30 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;93mWARNING [2024-06-17 18:17:30 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:17:32 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 18:18:09 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 18:18:09 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:18:09 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:18:09 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:18:09 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:18:09 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 18:18:14 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:18:14 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:18:14 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:18:14 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:18:15 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:18:15 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:18:15 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:18:15 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:18:15 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:18:15 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 18:18:15 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 18:18:15 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:18:15 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:18:15 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 18:18:15 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;93mWARNING [2024-06-17 18:18:46 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 18:18:48 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 18:18:50 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:18:50 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:18:50 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:18:50 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:18:50 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 18:19:52 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:19:52 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:19:52 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:19:52 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:19:53 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:19:53 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:19:53 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:19:53 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:19:53 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:19:53 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 18:19:53 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 18:19:53 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:19:53 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:19:53 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 18:19:53 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;93mWARNING [2024-06-17 18:19:54 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:19:55 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 18:20:16 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 18:20:18 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:20:18 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:20:18 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:20:18 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:20:18 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 18:20:19 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:20:19 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:20:19 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:20:19 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:20:20 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:20:20 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:20:20 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:20:20 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:20:20 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:20:20 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 18:20:20 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 18:20:20 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:20:20 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:20:20 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 18:20:20 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:20:20 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:20:22 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:20:24 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 18:22:49 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 18:22:50 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:22:50 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:22:50 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:22:50 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:22:50 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 18:22:52 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 18:22:52 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 18:22:52 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 18:22:52 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 18:22:53 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 18:22:53 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 18:22:53 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 18:22:53 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 18:22:53 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 18:22:53 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 18:22:53 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 18:22:53 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:22:53 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 18:22:53 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 18:22:53 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:24:17 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:24:19 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:24:21 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:24:24 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:24:25 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:24:30 - admin_manager.py:11] - callback data : manager:msg_timer:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 18:24:31 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 18:25:40 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 18:25:43 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 18:25:43 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 18:25:43 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 18:25:43 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 18:25:43 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 19:22:56 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 19:22:56 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 19:22:56 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 19:22:56 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 19:23:04 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 19:23:04 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 19:23:04 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 19:23:04 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 19:23:08 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 19:23:08 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 19:23:09 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 19:23:09 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 19:23:09 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 19:23:09 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 19:23:09 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 19:23:09 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 19:23:11 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 19:23:11 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 19:23:11 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 19:23:11 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 19:23:12 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 19:23:12 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 19:23:12 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 19:23:12 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 19:23:12 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 19:23:12 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 19:23:12 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 19:23:13 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 19:23:13 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 19:23:13 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 19:23:13 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 19:23:13 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 19:23:13 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 19:23:19 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:23:21 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:23:24 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:23:28 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 19:23:38 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 19:23:42 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 19:23:42 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 19:23:42 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 19:23:42 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 19:23:42 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 19:23:44 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 19:23:44 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 19:23:45 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 19:23:45 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 19:23:45 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 19:23:45 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 19:23:45 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 19:23:45 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 19:23:45 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 19:23:46 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 19:23:46 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 19:23:46 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 19:23:46 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 19:23:46 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 19:23:46 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 19:23:48 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:23:50 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:23:51 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:23:53 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-17 19:24:21 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 19:24:21 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 19:24:21 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 19:24:21 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 19:24:21 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 19:24:21 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 19:24:24 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 19:24:24 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 19:24:25 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 19:24:25 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 19:24:25 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 19:24:25 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 19:24:25 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 19:35:57 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:38:32 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:38:33 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 19:38:35 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 11:53:45 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-18 11:53:45 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 11:53:45 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 11:53:45 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 11:53:47 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 11:53:47 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 11:53:47 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 11:53:47 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 11:53:47 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 11:53:47 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 11:53:48 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 11:53:48 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-18 11:53:48 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-18 11:53:48 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 11:53:48 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 11:53:48 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 11:53:50 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 11:53:50 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 11:53:50 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 11:53:50 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 11:53:50 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 11:53:50 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 11:53:51 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 11:53:51 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 11:53:51 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 11:53:51 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 11:53:51 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 11:53:51 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-18 11:53:51 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-18 11:53:51 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 11:53:51 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 11:53:51 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-18 11:53:51 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 11:54:10 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:54:11 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:54:13 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:54:16 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:54:17 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-18 11:55:12 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:55:17 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:55:20 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:55:37 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:55:41 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:55:43 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:55:48 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 11:57:48 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;92mINFO [2024-06-18 11:57:51 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;92mINFO [2024-06-18 11:57:54 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;92mINFO [2024-06-18 11:57:56 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;92mINFO [2024-06-18 11:57:57 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:58:20 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:58:25 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:58:47 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:58:51 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:59:15 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 11:59:18 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;92mINFO [2024-06-18 12:00:23 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 12:00:25 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 12:00:29 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 12:00:46 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 12:00:52 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 12:01:13 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 12:01:16 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;92mINFO [2024-06-18 16:02:07 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-18 16:02:07 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:02:07 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:02:07 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 16:02:09 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 16:02:09 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:02:09 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:02:09 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:02:09 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 16:02:09 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:02:10 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:02:10 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-18 16:02:10 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-18 16:02:10 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:02:10 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:02:11 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:02:12 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 16:02:12 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:02:12 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:02:12 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:02:12 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:02:12 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:02:13 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:02:13 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:02:13 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:02:13 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:02:13 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:02:21 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-18 16:02:21 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-18 16:02:21 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:02:21 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:02:21 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-18 16:02:21 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:02:21 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:02:25 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:02:27 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:02:29 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 16:02:44 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-18 16:02:48 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:02:48 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:02:48 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:02:48 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:02:48 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-18 16:03:00 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:03:00 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:03:00 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:03:00 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:03:00 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:03:00 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:03:00 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:03:00 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:03:00 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:03:01 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-18 16:03:01 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-18 16:03:01 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:03:01 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:03:01 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-18 16:03:01 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:03:08 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:03:09 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:03:12 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:03:14 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:03:30 - admin_manager.py:11] - callback data : manager:auto_answer:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 16:16:01 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-18 16:16:06 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:16:06 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:16:06 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:16:06 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:16:06 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-18 16:16:33 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:16:33 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:16:33 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:16:33 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:16:34 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:16:34 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:16:34 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:16:34 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:16:34 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:16:34 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-18 16:16:34 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-18 16:16:34 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:16:34 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:16:34 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-18 16:16:34 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:16:40 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:16:42 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:16:44 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 16:17:00 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-18 16:17:04 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:17:04 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:17:04 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:17:04 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:17:04 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-18 16:17:05 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:17:05 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:17:05 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:17:05 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:17:06 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:17:06 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:17:06 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:17:06 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:17:06 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:17:06 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-18 16:17:06 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-18 16:17:06 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:17:06 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:17:06 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-18 16:17:06 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;93mWARNING [2024-06-18 16:17:07 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:17:10 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:17:11 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:17:48 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 16:17:48 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-18 16:17:48 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:17:48 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:17:48 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 16:17:50 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 16:17:50 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:17:50 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:17:50 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:17:51 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:17:51 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:17:51 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-18 16:17:51 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-18 16:17:51 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:17:51 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:17:51 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:17:54 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 16:17:54 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:17:54 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:17:54 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:17:54 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:17:54 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:17:54 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:17:54 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:17:54 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:17:54 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:17:54 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:18:02 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-18 16:18:04 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:18:04 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:18:04 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:18:04 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:18:04 - session.py:180] - Session stopped[0m
>>>>>>> auto-answer
[1;92mINFO [2024-06-18 16:19:47 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:19:47 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:19:47 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:19:47 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:19:47 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:19:47 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:19:47 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:19:47 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:19:47 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:19:48 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-18 16:19:48 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-18 16:19:48 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:19:48 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-18 16:19:48 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-18 16:19:48 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:19:49 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:19:51 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:19:52 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:19:54 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:19:56 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-18 16:19:57 - admin_manager.py:11] - callback data : manager:create_session:+46765147252  - user : 5522477996[0m
[1;92mINFO [2024-06-18 16:19:57 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-18 16:19:57 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:19:57 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:19:57 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 16:19:59 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 16:19:59 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:19:59 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:19:59 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:20:00 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:20:00 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:20:00 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-18 16:20:00 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-18 16:20:00 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:20:00 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:20:01 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:20:02 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-18 16:20:02 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:20:02 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-18 16:20:02 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-18 16:20:02 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-18 16:20:02 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-18 16:20:03 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-18 16:20:03 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-18 16:20:03 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-18 16:20:03 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-18 16:20:03 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-18 16:20:05 - account_manager.py:224] - Telegram says: [400 PHONE_CODE_INVALID] - The confirmation code is invalid (caused by "auth.SignIn")[0m
[1;92mINFO [2024-06-18 16:20:07 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-18 16:20:07 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-18 16:20:07 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-18 16:20:07 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-18 16:20:07 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-18 16:20:07 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:20:41 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-19 11:20:41 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:20:41 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:20:41 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-19 11:20:44 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-19 11:20:44 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:20:44 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:20:44 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:20:44 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-19 11:20:44 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:20:45 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:20:45 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:20:45 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-19 11:20:45 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:20:45 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:20:45 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:20:47 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-19 11:20:47 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:20:47 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:20:47 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:20:48 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:20:48 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:20:48 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:20:48 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:20:48 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:20:48 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:20:48 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:20:49 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:20:49 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:20:49 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:20:49 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:20:49 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:20:49 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:22:35 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:22:38 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:22:38 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:22:38 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:22:38 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:22:38 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:22:40 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:22:40 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:22:40 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:22:40 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:22:41 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:22:41 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:22:41 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:22:41 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:22:41 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:22:41 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:22:41 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:22:41 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:22:41 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:22:41 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:22:41 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:23:04 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:23:06 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:23:06 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:23:06 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:23:06 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:23:06 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:23:08 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-19 11:23:08 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:08 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:08 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:11 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-19 11:23:11 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:23:11 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:11 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:11 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:11 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:23:12 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:23:12 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:23:12 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-19 11:23:12 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:12 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:12 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:14 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-19 11:23:14 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:23:14 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:14 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:14 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:14 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:23:15 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:23:15 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:23:15 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:23:15 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:23:15 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:23:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:23:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:23:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:23:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:23:17 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:23:17 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:23:17 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:23:20 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:23:28 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:23:33 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-19 11:23:33 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:33 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:33 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:35 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-19 11:23:35 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:23:35 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:35 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:35 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:35 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:23:36 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:23:36 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:23:36 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-19 11:23:36 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:36 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:36 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:39 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-19 11:23:39 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:23:39 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:23:39 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:23:39 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:23:39 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:23:40 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:23:40 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:23:40 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:23:40 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:23:40 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-19 11:23:53 - account_manager.py:354] - Telegram says: [401 SESSION_PASSWORD_NEEDED] - The two-step verification is enabled and a password is required (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-19 11:24:00 - account_manager.py:363] - BAGY9NIAJYi44vq_QrhvGbDIKBO7Qp305Duz1JtExCgDKAku_mc8owqFU_DJ1COj14KzWnkUlbm83Y3ZEVBalS_4wSM9Ge1JlmF6MNC7OA5VNO0dEG8pPIunvrpHB9_ooumwGqRVsbatM_sNbgidALEetHPC0STFcXQAd3EL3CycUrIGFX8r-dVQJyLEWufXrNz2W6EiwgPfU0yM74RDTMwoq-IX12K_Eui8pzWwEF0cxWCh8AuD_SqR3yjqz8y10YVqAS6b7vmljCnAu4x0Gm0-voleHDtcZa4kXnLdy1S5YI59vZ_-2Y4cAHEVkMBXSW3u62kpG9sr1WhXevdtqx9YySof6AAAAAFJKlOsAA[0m
[1;92mINFO [2024-06-19 11:24:00 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:24:00 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:24:00 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:24:00 - session.py:180] - Session stopped[0m
[1;93mWARNING [2024-06-19 11:24:01 - utils.py:75] - running container for phone : +13182391021[0m
[1;93mWARNING [2024-06-19 11:24:03 - admin_manager.py:11] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:24:07 - admin_manager.py:11] - callback data : manager:status_account:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:24:08 - admin_manager.py:11] - callback data : manager:status_account:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:24:12 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:24:15 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:24:15 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:24:15 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:24:15 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:24:15 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:28:54 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:28:54 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:28:55 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:28:55 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:28:55 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:28:55 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:28:55 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:28:55 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:28:55 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:28:56 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:28:56 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:28:56 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:28:56 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:28:56 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:28:56 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:29:00 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:29:02 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:29:05 - admin_manager.py:11] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:29:06 - admin_manager.py:11] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:34:31 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:34:36 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:34:36 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:34:36 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:34:36 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:34:36 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:34:38 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:34:38 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:34:39 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:34:39 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:34:39 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:34:39 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:34:39 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:34:39 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:34:39 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:34:52 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:34:52 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:34:53 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:34:53 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:34:53 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:34:53 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:34:53 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:34:53 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:34:53 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:34:54 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:34:54 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:34:54 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:34:54 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:34:54 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:34:54 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:35:06 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:35:09 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:35:11 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:35:13 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:37:32 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:37:34 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:37:34 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:37:34 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:37:34 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:37:34 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:37:35 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:37:35 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:37:35 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:37:35 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:37:36 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:37:36 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:37:36 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:37:36 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:37:36 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:37:36 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:37:36 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:37:36 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:37:36 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:37:36 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:37:36 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:37:40 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:37:42 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:37:44 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:37:45 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:38:03 - admin_manager.py:12] - callback data : manager:back_account:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:40:22 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:40:26 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:40:26 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:40:26 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:40:26 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:40:26 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:40:28 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:40:28 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:40:28 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:40:28 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:40:28 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:40:28 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:40:28 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:40:28 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:40:28 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:40:29 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:40:29 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:40:29 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:40:29 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:40:29 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:40:29 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:40:31 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:40:33 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:40:35 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:40:37 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:40:38 - admin_manager.py:12] - callback data : manager:back_account:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:40:58 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:40:58 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:40:58 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:40:58 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:40:58 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:40:58 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:41:01 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:41:01 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:41:01 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:41:01 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:41:01 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:41:01 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:41:01 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:41:01 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:41:01 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:41:02 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:41:02 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:41:02 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:41:02 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:41:02 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:41:02 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:41:04 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:06 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:08 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:09 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:11 - admin_manager.py:12] - callback data : manager:back_account:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:14 - admin_manager.py:12] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:15 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:17 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:41:36 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:38 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:40 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:41 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:48 - admin_manager.py:12] - callback data : manager:back_account:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:51 - admin_manager.py:12] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:52 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:55 - admin_manager.py:12] - callback data : manager:status_account:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:41:58 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:42:07 - admin_manager.py:12] - callback data : manager:back_account:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:42:08 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:42:34 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:42:36 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:42:36 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:42:36 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:42:36 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:42:36 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:42:42 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:42:42 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:42:42 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:42:42 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:42:43 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:42:43 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:42:43 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:42:43 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:42:43 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:42:43 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:42:43 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:42:43 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:42:43 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:42:43 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:42:43 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;93mWARNING [2024-06-19 11:42:46 - admin_manager.py:12] - callback data : manager:back_account:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:42:47 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:46:11 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:46:11 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:46:11 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:46:11 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:46:11 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:46:11 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:46:13 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:46:13 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:46:13 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:46:13 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:46:14 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:46:14 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:46:14 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:46:14 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:46:14 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:46:14 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:46:14 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:46:14 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:46:14 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:46:14 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:46:14 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;93mWARNING [2024-06-19 11:46:17 - admin_manager.py:12] - callback data : manager:back_account:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:46:19 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:47:07 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:47:09 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:47:09 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:47:09 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:47:09 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:47:09 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:47:11 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:47:11 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:47:12 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:47:12 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-19 11:47:13 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:47:13 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:47:13 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:47:13 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:47:13 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:47:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-19 11:47:17 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-19 11:47:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:47:17 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-19 11:47:17 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-19 11:47:17 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:47:17 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;92mINFO [2024-06-19 11:47:18 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:47:19 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:47:22 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:47:24 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:47:26 - admin_manager.py:12] - callback data : manager:user_manager:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:47:38 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:47:45 - admin_manager.py:12] - callback data : manager:accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:47:55 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:47:55 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:47:55 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:47:55 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:47:55 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:47:55 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:48:00 - session.py:404] - [1] Retrying "messages.EditMessage" due to: Request timed out[0m
[1;93mWARNING [2024-06-19 11:48:05 - connection.py:50] - Unable to connect due to network issues: Socket error: timed out[0m
[1;92mINFO [2024-06-19 11:48:06 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:48:06 - connection.py:47] - Connecting...[0m
[1;93mWARNING [2024-06-19 11:48:16 - connection.py:50] - Unable to connect due to network issues: Socket error: timed out[0m
[1;92mINFO [2024-06-19 11:48:17 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:48:17 - connection.py:47] - Connecting...[0m
[1;93mWARNING [2024-06-19 11:48:27 - connection.py:50] - Unable to connect due to network issues: Socket error: timed out[0m
[1;93mWARNING [2024-06-19 11:48:28 - connection.py:61] - Connection failed! Trying again...[0m
[1;92mINFO [2024-06-19 11:48:28 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:48:28 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:48:28 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:48:28 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:48:31 - session.py:404] - [2] Retrying "messages.EditMessage" due to: Request timed out[0m
[1;93mWARNING [2024-06-19 11:48:38 - connection.py:50] - Unable to connect due to network issues: Socket error: timed out[0m
[1;92mINFO [2024-06-19 11:48:39 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:48:39 - connection.py:47] - Connecting...[0m
[1;93mWARNING [2024-06-19 11:48:49 - connection.py:50] - Unable to connect due to network issues: Socket error: timed out[0m
[1;92mINFO [2024-06-19 11:48:50 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:48:50 - connection.py:47] - Connecting...[0m
[1;93mWARNING [2024-06-19 11:49:00 - connection.py:50] - Unable to connect due to network issues: Socket error: timed out[0m
[1;92mINFO [2024-06-19 11:49:01 - session.py:404] - [3] Retrying "messages.EditMessage" due to: Request timed out[0m
[1;93mWARNING [2024-06-19 11:49:01 - connection.py:61] - Connection failed! Trying again...[0m
[1;92mINFO [2024-06-19 11:49:01 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:49:01 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-19 11:49:01 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-19 11:49:01 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-19 11:49:02 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-19 11:49:02 - session.py:294] - NetworkTask started[0m
[1;93mWARNING [2024-06-19 11:49:03 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:49:03 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;93mWARNING [2024-06-19 11:49:03 - admin_manager.py:12] - callback data : manager:manage:+13182391021  - user : 5522477996[0m
[1;92mINFO [2024-06-19 11:49:03 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-19 11:49:03 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-19 11:49:03 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-19 11:49:03 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-19 11:49:03 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-19 11:49:30 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-19 11:49:33 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-19 11:49:33 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-19 11:49:33 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-19 11:49:33 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-19 11:49:33 - session.py:180] - Session stopped[0m
