[1;92mINFO [2024-06-17 07:19:29 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:19:29 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:29 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:29 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:30 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:19:30 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:19:30 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:30 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:19:31 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:19:31 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:19:31 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:31 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:33 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:19:33 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:19:33 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:19:33 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:19:34 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:19:34 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:19:35 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:19:35 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:19:36 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:19:37 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:19:39 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:19:46 - start_command.py:32] - user not admin : 232443605[0m
[1;92mINFO [2024-06-17 07:19:48 - start_command.py:32] - user not admin : 232443605[0m
[1;92mINFO [2024-06-17 07:20:09 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:11 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:13 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:14 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:20:16 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:20:22 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:20:22 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:22 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:22 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:24 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:20:24 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:20:24 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:24 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:24 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:24 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:20:25 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:20:25 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:20:25 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:20:25 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:25 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:25 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:27 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:20:27 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:20:27 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:20:27 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:20:27 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:20:27 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:20:28 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:20:43 - account_manager.py:245] - Telegram says: [400 PHONE_CODE_INVALID] - The confirmation code is invalid (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-17 07:20:56 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:21:15 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:21:24 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:21:24 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:24 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:24 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:26 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:21:26 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:26 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:26 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:26 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:26 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:21:27 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:21:27 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:21:27 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:21:27 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:27 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:28 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:29 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:21:29 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:29 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:21:29 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:21:29 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:21:29 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:21:30 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:21:37 - account_manager.py:200] - Telegram says: [401 SESSION_PASSWORD_NEEDED] - The two-step verification is enabled and a password is required (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-17 07:21:43 - account_manager.py:225] - Telegram says: [400 USERNAME_NOT_OCCUPIED] - The username is not occupied by anyone (caused by "contacts.ResolveUsername")[0m
[1;92mINFO [2024-06-17 07:21:43 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:21:43 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:21:43 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:21:43 - session.py:180] - Session stopped[0m
[1;93mWARNING [2024-06-17 07:21:43 - utils.py:72] - running container for phone : +46765147252[0m
[1;92mINFO [2024-06-17 07:21:56 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:21:58 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:24:01 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:24:03 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:24:03 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:24:03 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:24:03 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:24:03 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:24:42 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:42 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:24:42 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:24:42 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:24:43 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("account_manager_handler") in group 1 from "plugins.account_manager"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] CallbackQueryHandler("admin_manager_handler") in group 0 from "plugins.admin_manager"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] MessageHandler("start_manager") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:698] - [selfbot] [LOAD] MessageHandler("user_not_admin") in group 0 from "plugins.start_command"[0m
[1;92mINFO [2024-06-17 07:24:43 - client.py:775] - [selfbot] Successfully loaded 4 plugins from "plugins"[0m
[1;92mINFO [2024-06-17 07:24:43 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:24:46 - start_command.py:16] - command : /start   -   user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:24:47 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:24:49 - admin_manager.py:11] - callback data : manager:add_account  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:24:57 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-06-17 07:24:57 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:57 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:24:57 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:24:58 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:24:58 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:24:58 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:58 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:24:59 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:24:59 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:24:59 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:24:59 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-06-17 07:24:59 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:24:59 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:25:00 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:25:02 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-06-17 07:25:02 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:25:02 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-06-17 07:25:02 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-06-17 07:25:02 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-06-17 07:25:02 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:155] - Session started[0m
[1;92mINFO [2024-06-17 07:25:03 - session.py:272] - PingTask started[0m
[1;93mWARNING [2024-06-17 07:25:08 - account_manager.py:185] - Telegram says: [401 SESSION_PASSWORD_NEEDED] - The two-step verification is enabled and a password is required (caused by "auth.SignIn")[0m
[1;93mWARNING [2024-06-17 07:25:12 - account_manager.py:194] - BAGY9NIAFoEHRPlSUjkmVgVcApezwK-h0ZPb2XA7FQ-3_tIeC-f9ql0QuZviujF5HuBP4_jgg_pCXuc46dGCqD0cv0nfB_N32Fb0VRqBYDSv3ENowOUBB7YakP--786EG35FkwdPLuI5-KXKBMRX4V9aSNd_Z7DyoaefTlVlph4K5j0nSlMJnDZ0sdVFKN8xSrYMHh4NaNsylkkO4YnCwOSoixNZn-KQXSt_99ICuWUa2hS3wgG-HJl2eCTpQsTWhWY_VR942ZdK8_IPRUBYQYqQDUMVcAfH_VUjMgbwwvJF7S6OfF0-wLo0HM_Fvkp9h3ns8-Lqkf6lKkGAJLefacLk4L0KlQAAAAFIjDkpAA[0m
[1;92mINFO [2024-06-17 07:25:12 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:25:12 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:25:12 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:25:12 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-06-17 07:25:13 - start_command.py:32] - user not admin : 5512116521[0m
[1;93mWARNING [2024-06-17 07:25:13 - utils.py:72] - running container for phone : +46765147252[0m
[1;93mWARNING [2024-06-17 07:25:15 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:17 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:19 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:20 - admin_manager.py:11] - callback data : manager:status_account:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:22 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:23 - admin_manager.py:11] - callback data : manager:back  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:26 - admin_manager.py:11] - callback data : manager:accounts  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:28 - admin_manager.py:11] - callback data : manager:manage:+46765147252  - user : 5522477996[0m
[1;93mWARNING [2024-06-17 07:25:29 - admin_manager.py:11] - callback data : manager:back_to_accounts  - user : 5522477996[0m
[1;92mINFO [2024-06-17 07:25:43 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-06-17 07:25:43 - dispatcher.py:167] - Stopped 8 HandlerTasks[0m
[1;92mINFO [2024-06-17 07:25:43 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-06-17 07:25:43 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-06-17 07:25:43 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-06-17 07:25:43 - session.py:180] - Session stopped[0m
